### ISSUE TITLE
[500 Can't connect to www.googleapis.com:443] Error occured...

### ISSUE THREAD

**Issue by hasufell** [trizen/youtube-viewer#103]
Happens on pretty much everything (starting video, searching,...). I have all dependencies installed. Perl-5.20.2.

**Comment by hasufell** [comment]
Other programs (such as livestreamer) don't have any problem.

**Comment by trizen** [comment]
I can't confirm the issue here. I suspect it's something temporary related to the local Google servers.

A few things to try would be to `--logout` and `--login` afterwards and also install the `Mozilla::CA` module (just in case the issue is related to SSL verification, which is quite unlikely given the error code).

**Comment by hasufell** [comment]
`Mozilla::CA` is installed. I don't have a yt account anyway. And the problem still persists.

I can still watch yt via browser, livestreamer and other methods.

**Comment by hasufell** [comment]
I cannot reproduce this anymore, so probably local foo or a broken Module that has been fixed.
