### ISSUE TITLE
Highlight watched videos

### ISSUE THREAD

**Issue by zunder** [trizen/youtube-viewer#119]
Is there a way to mark already watched videos in the list? On YouTube's page those videos are shown as already seen. Obviously one has to login in order to get this feature. Can it be done in youtube-viewer as well?

**Comment by trizen** [comment]
Very good suggestion. Currently, there is no option for this, but it may happen very soon.

**Comment by trizen** [comment]
The `--highlight` option has been successfully added, along with two config options:

 * `highlight_watched`  -- turns on or off the highlight feature
 * `highlight_color`    -- specifies a color for the highlight feature (default: "bold")

A color can be anything that is supported by [Term::ANSIColor](https://metacpan.org/pod/Term::ANSIColor):

```perl
highlight_color => 'red on_black',	# red text on black background
highlight_color => 'bold italic',   # italic bold text
```

I forgot to mention initially, there is a similar option, called `--autohide`, which automatically hides watched videos, instead of highlighting them. It may be used as an alternative.
