### ISSUE TITLE
Getting error while playing videos

### ISSUE THREAD

**Issue by mafiya69** [trizen/youtube-viewer#123]
Hi there, I tried to play videos using [youtube-viewer](https://github.com/trizen/youtube-viewer).
I got the following error while selecting video : 
```
do_connect: could not connect to socket                                         
connect: No such file or directory  
```
Have a look at [this](https://asciinema.org/a/00d7ed0idb62oalrxaur9g938) at 00:12.

I am using Fedora 24 and downloaded from [here](https://build.opensuse.org/package/show/home:zhonghuaren/youtube-viewer).

**Comment by trizen** [comment]
Hi. This error seems to come from `mplayer`. Some old versions are known to not being able to handle https streams. Also, that particular video uses an encrypted signature, which can be played only if `youtube-dl` is installed (preferably, the latest/git version).

If the error persists after `youtube-dl` is installed, I recommend to install and use `mpv` instead of `mplayer`, by executing `youtube-viewer --player=mpv`.

(Additionally, please consider updating `youtube-viewer` to its latest version, which currently is 3.2.2)

**Comment by mafiya69** [comment]
Thanks, its now working with `youtube-viewer --player=mpv`!

**Comment by trizen** [comment]
Awesome! :)
