### ISSUE TITLE
Weird behavior

### ISSUE THREAD

**Issue by Germoluso** [trizen/youtube-viewer#131]
OS: Ubuntu 14.04 64 bits

GTK Youtube Viewer works out of the box with me (provided I tweak the .config file so it can properly use mplayer, as instructed elsewhere), and I want to thank you for this fantastic piece of software.

That said, the program has a recurrent strange behavior, in that sometimes, at seemingly random intervals, it opens with only the toolbar and the "Thumbnails/Title/Info bar visible, everything else, blank, and I can't do anything with the program other than open and close it, and play with the "Menu" and "Help" options in the Unity toolbar.

![screenshot from 2016-12-02 18 22 15](https://cloud.githubusercontent.com/assets/24321800/20845356/973c446c-b8bc-11e6-93d4-e35e32f2f4b7.png)

I've found that deleting the .conf folder sets everything back to normal, but then I have to reedit the .config file so mplayer can play videos, and it's somewhat aggravating. Have you heard of similar issues before? Any idea how I can prevent it from happening?

Thanks in advance for any help you might provide.

**Comment by trizen** [comment]
Thank you for your appreciation and for reporting this issue. This is the first time when I read about this strange behavior.

Although I'm not able to duplicate the issue, a possible scenario, which fits your description, is the following: 

1. the file `~/.config/youtube-viewer/categories-us-en_US.json` can't be created by gtk-youtube-viewer or it gets deleted by some other program
2. when gtk-youtube-viewer is executed, it tries to create this file, requesting the data from YouTube
3. the YouTube servers fail to respond in a reasonable amount of time
4. gtk-youtube-viewer stays frozen, until YouTube responds.

Interestingly is that after deleting the config directory, everything works correctly.

Some ideas to prevent this from happening, are the following:
- Try to always close gtk-youtube-viewer normally, especially before powering off the computer. (otherwise, it may result in a corrupted config file)
- Make sure the file `~/.config/youtube-viewer/categories-us-en_US.json` exists and does not get deleted by some cleaning tools (unlikely, but possible).

I'm interested to hear if someone else had this issue before.

**Comment by Germoluso** [comment]
Thanks for your reply. I've been paying attention to the .conf file, and here's what I've noticed happens whenever the issue occurs:
- hpaned_position changes from the default 420 to 1914
- mainw_maximized is set from 0 to 1
If I set both back to their defaults, the program starts working ok again.

Also, sometimes, a youtube-viewer.conf file will be created alongside the gtk-youtube-viewer.conf file. It doesn't seem to affect the program, though.

Any idea what might cause this and how I can prevent it from happening?

**Comment by trizen** [comment]
It seems like the `hpaned_position` is calculated and stored incorrectly, rendering the right-side pane invisible to the user. You should, however, be able to drag the pane with the mouse from the right margin of the window.

The value of `mainw_maximized` seems ok: it gets set to 1 when the main window of gtk-youtube-viewer is maximized.

Try this to see if it fixes the issue: locate the [line 835](https://github.com/trizen/youtube-viewer/blob/90ee1b0c19574b773c81bc260e9441d9b3edb5fd/bin/gtk-youtube-viewer#L835) in `/usr/bin/gtk-youtube-viewer`:

```perl
    $hbox2->set_position($CONFIG{hpaned_position}); 
```

and either comment it out or replace `$CONFIG{hpaned_position}` with a constant, like:
```perl
    $hbox2->set_position(1600); 
```

**Comment by Germoluso** [comment]
Deleting the line seems to have done the trick and the program is working fine now. Cheers :+1:
