### ISSUE TITLE
gtk-youtube-viewer: browsing author's video -> can't played

### ISSUE THREAD

**Issue by notramo** [trizen/youtube-viewer#154]
1. search for anything in gtk-youtube-viewer
2. right click on a video -> Author -> Uploads
3. none of the results can be played

**Comment by trizen** [comment]
I can't reproduce this issue. Try to install the latest git version to see if it is already fixed.

**Comment by notramo** [comment]
The latest git version works, but I didn't find a commit related to it since my previously installed version.

**Comment by trizen** [comment]
This issue was introduced during the addition of the support for full descriptions to videos ([here](https://github.com/trizen/youtube-viewer/commit/410ec12482bfaeca0548ec7dce47a97f6a196326)) and was fixed a commit after ([here](https://github.com/trizen/youtube-viewer/commit/844f646769ffa37661a33236d51f2f3e1f3ea6a9)).
