### ISSUE TITLE
How did you make videos start up so fast?

### ISSUE THREAD

**Issue by ReekyMarko** [trizen/youtube-viewer#239]
Hi! I'm normally using straight mpv to watch youtube videos and one thing that annoys me that the startup time for most videos is 5 to 10 seconds. Just discovered this project and noticed that the videos usually start in below 2 seconds. Is this something we could contribute back to youtube-dl? I realize this project is written in perl and youtube-dl is written in python and there must be a list of other limitations, but just some food for thought.

For now I think I will route my youtube links through youtube-viewer with xdg-open :smile_cat:

**Comment by trizen** [comment]
Hi. I think there are a couple of main things that contribute to this:

1. No JavaScript code is executed by `youtube-viewer`.
2. Videos with encrypted signatures are not supported (unless `youtube-dl` is installed).

Also notice that `youtube-dl` has a considerably higher start-up time than `youtube-viewer`:

```console
% time youtube-dl --version                                            » /tmp «
2019.01.17
youtube-dl --version  0.38s user 0.05s system 99% cpu 0.436 total
```

```console
% time youtube-viewer --version                                        » /tmp «
YouTube Viewer 3.5.1
youtube-viewer --version  0.09s user 0.00s system 96% cpu 0.095 total
```

For videos with non-encrypted signatures, `youtube-viewer` uses only the `get_video_info` undocumented URL, without executing `youtube-dl`, and then passes the extracted audio/video urls to `mpv` (along with the `--no-ytdl` flag, so `youtube-dl` is not executed unnecessarily), which is why this is generally faster than `mpv [youtube-url]`, which always executes `youtube-dl`.

However, notice that `youtube-dl` is not really that slow, suggesting that maybe the start-up time of a video can also be improved in `mpv`.

- youtube-dl (~2.6s):
```console
% time youtube-dl --all-formats --dump-single-json https://www.youtube.com/watch\?v\=o8NPllzkFhE             » /tmp «
...
youtube-dl --all-formats --dump-single-json   1.41s user 0.07s system 57% cpu 2.567 total
```

- youtube-viewer (~1.4s):
```console
% time youtube-viewer --extract='*VIDEO*' --no-interactive https://www.youtube.com/watch\?v\=o8NPllzkFhE                                        » /tmp «
...
youtube-viewer --extract='*VIDEO*' --no-interactive   0.63s user 0.04s system 49% cpu 1.351 total
```

For videos with encrypted signatures, `youtube-viewer` is slower than `youtube-dl` (as it has to execute `youtube-dl` to get the audio/video urls):

```console
%  time youtube-viewer --extract='*VIDEO*' --no-interactive https://www.youtube.com/watch\?v\=j5-yKhDd64s              » /tmp «
2019.01.17
...
youtube-viewer --extract='*VIDEO*' --no-interactive   2.32s user 0.23s system 49% cpu 5.137 total
```

Hopefully, this answers your question.

**Comment by ReekyMarko** [comment]
Thanks for the extensive writeup! Now that I think of it more, youtube-dl probably needs to support a metric ton of features more than youtube-viewer, so it only makes sense that youtube-viewer is considerably faster.
