### ISSUE TITLE
Add option to specify video fps.

### ISSUE THREAD

**Issue by SGOrava** [trizen/youtube-viewer#274]
youtube-dl has an option to specify fps of the video which should be downloaded.
Is it possible to add into youtube-viewer ?
Right now the yt-viewer is trying to use 60fps video on my small machine and it is unwatchable.
While youtube.dl can clearly download 30fps one.

So having an option like "preffer fps: [30 / 60]" would be nice.

https://github.com/ytdl-org/youtube-dl/blob/master/README.md#format-selection

**Comment by trizen** [comment]
Will not add an explicit option for this, as it will unnecessarily complicate the code, since most people prefer 60 FPS anyway. (see: https://github.com/trizen/youtube-viewer/issues/67)

However, adding the following player entry, will do the trick:

```perl
mpv30fps => {
    fs => "--fullscreen",
    novideo => "--no-video",
    srt => "--sub-file *SUB*",
    arg => "--ytdl-raw-options='format=best[fps<=30]+bestaudio/best[height<=720]' *URL*",
    cmd => "mpv",
},
```

By executing youtube-viewer with `--player=mpv30fps`, videos will be played @ 30 FPS (or lower).
