### ISSUE TITLE
Open in same MPV/VLC instance already running.

### ISSUE THREAD

**Issue by squidds** [trizen/youtube-viewer#318]
Great application! It makes YouTube amazing on the pi 4 on ManjaroARM.

This is not really an issue but wasn't sure where to get info on my question. When I changed the player to VLC in the config file, nothing happens. I wanted to try VLC for testing purposed. 

Also, is there a way to open the videos in the same MPV instance, rather than opening a new MPV window every time. So if I'm in the middle of a video, and want to go to another, it replaces the video that's already playing?

Thanks again, great application!

**Comment by Isti115** [comment]
I would also really prefer an option to reuse the player instances (either MPV or VLC), since I'm using this app for listening to music, and would like to have it on a specific container in a specific workspace, but for every new video it reopens in the workspace I'm currently on.

Thanks for this awesome piece of software, it helps reduce distraction by not constantly showing related videos and such! :)

**Comment by kortewegdevries** [comment]
This would be easy to do if Trizen supports `umpv` as a player: https://raw.githubusercontent.com/mpv-player/mpv/master/TOOLS/umpv

**Comment by kortewegdevries** [comment]
This would be easy to do with `umpv` as a player: https://raw.githubusercontent.com/mpv-player/mpv/master/TOOLS/umpv

For VLC there is `--one-instance`

**Comment by kortewegdevries** [comment]
Off topic: 
For files we can use `umpv` as a player to force single instance mode, it doesn't intercept links I think....

**Comment by fockboi-lgtm** [comment]
Would this possible for `youtube-viewer`? Easier to use when using tiling managers and assigning work-spaces for video players. 
Existing solutions using `umpv` and `bash scripts` didn't work well.
