### ISSUE TITLE
Oauth

### ISSUE THREAD

**Issue by Bhooty** [trizen/youtube-viewer#353]
I installed the app on manjaro linux
i got the api like the steps but i am unable to get the auth client id and client secret
can u plz help?
also on the app there is a login to youtube oauth link but it doesn't open or forward to  browser for login
help needed!! :(

**Comment by trizen** [comment]
In order to log in, replace `CLIENT_ID` and `CLIENT_SECRET` with your native client ID and client secret values, by creating a new OAuth 2.0 Client ID [here](https://console.developers.google.com/apis/api/youtube.googleapis.com/credentials): click "Create Credentials" > "OAuth client ID", then select "Desktop app".

I attached below some screenshots for guidance:

1. Select the corresponding project name, then click "+ Create credentials"
![2021-01-20-141733_1920x1080_scrot](https://user-images.githubusercontent.com/614513/105174627-be9a6980-5b1a-11eb-837a-57b8929c6d33.png)

2. Select "Oauth ID"
![2021-01-20-141744_1920x1080_scrot](https://user-images.githubusercontent.com/614513/105174634-c1955a00-5b1a-11eb-8908-ed35b059f2fa.png)

3. Select "Desktop app"
![2021-01-20-141805_1920x1080_scrot](https://user-images.githubusercontent.com/614513/105174638-c3f7b400-5b1a-11eb-9666-4d6444bf106e.png)

4. Click "Create"
![2021-01-20-141820_1920x1080_scrot](https://user-images.githubusercontent.com/614513/105174645-c6f2a480-5b1a-11eb-9fdf-f59552732837.png)

5. Copy the client ID and client secret values and place them into the `api.json` file.
![2021-01-20-141837_1920x1080_scrot](https://user-images.githubusercontent.com/614513/105174654-c954fe80-5b1a-11eb-9ed4-773ca1a9a720.png)

**Comment by Bhooty** [comment]
on step 3 it asks for me to configure the consent screen
![image](https://user-images.githubusercontent.com/46019727/105178061-c0cbea80-5b51-11eb-83d0-921f89ba8781.png)

if i click it
![image](https://user-images.githubusercontent.com/46019727/105178232-f53fa680-5b51-11eb-9959-aa9a3536c81d.png)

i choose external then create and then stuck

**Comment by trizen** [comment]
Select "External"

**Comment by Bhooty** [comment]
do i do anything here?

![Uploading image.png…]()

**Comment by trizen** [comment]
Scope should be "https://www.googleapis.com/auth/youtube.force-ssl".

See also: https://developers.google.com/youtube/v3/guides/auth/installed-apps

**Comment by Bhooty** [comment]
do i add test user?

**Comment by trizen** [comment]
It looks like you sent the app for review. Undo that if you did.

See also: https://www.videoconverterfactory.com/kodi/youtube-api-key.html

If everything is OK, you should be able to log in, as illustrated in the following screenshots:

![2021-01-20-155938_1920x1080_scrot](https://user-images.githubusercontent.com/614513/105184899-cd3b4d80-5b27-11eb-84be-0c1b6ebd19c5.png)

![2021-01-20-154554_1920x1080_scrot](https://user-images.githubusercontent.com/614513/105184937-da583c80-5b27-11eb-842e-b8f31eada2d5.png)

![2021-01-20-154602_1920x1080_scrot](https://user-images.githubusercontent.com/614513/105185023-f5c34780-5b27-11eb-88d2-99b8a05a7cc1.png)

![2021-01-20-154611_1920x1080_scrot](https://user-images.githubusercontent.com/614513/105185136-19868d80-5b28-11eb-997f-7e2784ab55d2.png)

![2021-01-20-155126_1920x1080_scrot](https://user-images.githubusercontent.com/614513/105185168-1f7c6e80-5b28-11eb-909e-0983338e6419.png)

![2021-01-20-155515_1920x1080_scrot](https://user-images.githubusercontent.com/614513/105185222-2b683080-5b28-11eb-96b5-a174573a4f7e.png)

**Comment by Bhooty** [comment]
yes got it to work
thanks!

**Comment by PalanixYT** [comment]
guys can you help me? i did everything just like you did, and it worked, but there is just one problem. i can't click the link to get the authentication code. when i click it, nothing happens

**Comment by trizen** [comment]
Try right-click -> "Copy URL", then paste the copied URL into a browser.
![2021-02-13-034724_1920x1080_scrot](https://user-images.githubusercontent.com/614513/107838353-6fec9200-6d9d-11eb-83b1-916fa39af698.png)

**Comment by PalanixYT** [comment]
sadly that doesn't work. i have tried it using all gtk versions. could it be because of wayland?

**Comment by trizen** [comment]
Not sure, but double-check the `api.json` file. If everything looks alright, then you can try to log-in from the CLI version:

```console
youtube-viewer --login
```

**Comment by PalanixYT** [comment]
Can't locate object method "history_list" via package "Term::ReadLine::Stub" at /usr/bin/vendor_perl/youtube-viewer line 655.

**Comment by trizen** [comment]
It seems that you don't have `Term::ReadLine::Gnu`.

Either install [Term::ReadLine::Gnu](https://metacpan.org/release/Term-ReadLine-Gnu), or set `history => 0` in the configuration file of `youtube-viewer` (`/.config/youtube-viewer/youtube-viewer.conf`).

**Comment by PalanixYT** [comment]
thanks man it worked

**Comment by zensubz** [comment]
I think YouTube/Google has recently made some changes, the above tips aren't working for me now. It is asking for Developer Contact, domain name etc., and also forces one to apply for 'project review/verification', thereby making it complicated. This has happened the moment I enabled this scope: ```https://www.googleapis.com/auth/youtube.force-ssl```. Here is the screenshot of the login-error:
![gtkyt_error](https://user-images.githubusercontent.com/5127872/166150118-42697244-a86d-4d93-ad57-eb9d3cc9ea5c.jpg)

I request @trizen to look into this issue and give the solution. Thanks.

**Comment by zensubz** [comment]
Thanks @trizen for the work on aab839b. This time I could go a bit further, allow the app to gain access, but after that it doesn't redirect, I have attached the screenshots below:
![ytv_access](https://user-images.githubusercontent.com/5127872/166154773-426e3a24-9a74-4d74-bd05-9bdaeb088ef4.jpg)
![ytv_error](https://user-images.githubusercontent.com/5127872/166154777-abd6b0e6-775a-42e2-976a-172d041489f2.jpg)

Am I missing something..?

**Comment by iwbcman** [comment]
Just wanted to mention, [https://developers.google.com/identity/protocols/oauth2/limited-input-device#creatingcred](url) worked for me
