### ISSUE TITLE
ADD Resolution="config" option to use default youtube-dl config #gtk

### ISSUE THREAD

**Issue by allanlaal** [trizen/youtube-viewer#361]
## use case:

I choose a resolution of 480p.
but the video only has 720p and 1080p available

## Expected

should default to next available step down, then up from 480p:
out of a selection of [720p, 1080p] defaults to 720p
out of a selection of [360p, 720p, 1080p] defaults to 360p

## Actual

defaults to resolution[0] (probably), which in youtube might even be 4K

**Comment by allanlaal** [comment]
this might only affect gtk-youtube-viewer/

**Comment by allanlaal** [comment]
it seems atleast the resolution section of the options in ~/.config/youtube-dl/config are overridden by youtube-viewer

**Comment by allanlaal** [comment]
it seems atleast the resolution section of the options in ~/.config/youtube-dl/config are overridden by youtube-viewer.

could we add an option named "default" or "config" to the Resolution list, so (gtk-)youtube-viewer would not override it?

**Comment by trizen** [comment]
Can you include a video link for testing? Thanks!

**Comment by allanlaal** [comment]
https://www.youtube.com/watch?v=b5bBuEN2o2Q

it seems this video did have 360p available, so I updated the defaulting behaviour:
should default to next available step down, then up from 480p:
out of a selection of [720p, 1080p] defaults to 720p
out of a selection of [360p, 720p, 1080p] defaults to 360p

**Comment by allanlaal** [comment]
since this is somewhat of an edge case, I think implementing a Resolution="config" option for ppl like me is enough

**Comment by trizen** [comment]
It is possible to pass the YouTube URL directly to `mpv`, which uses `youtube-dl` under the hood (below is an example for playing videos at resolution <= 480p):

```perl
 video_player_selected => "mpv_native",
 video_players         => {
                   mpv_native => {
                                  arg => "--really-quiet --ytdl-format='bestvideo[height<=480]+bestaudio/best' --force-media-title=*TITLE* *URL*",
                                  cmd => "mpv",
                                  fs  => "--fullscreen",
                                  srt => "--sub-file=*SUB*",
                                 },
                  },
```

Since `youtube-viewer` has its [own mechanism](https://github.com/trizen/youtube-viewer/blob/master/lib/WWW/YoutubeViewer/Itags.pm) for selecting the resolution of videos (`youtube-dl` is only used for certain types of videos to extract the video URLs, but not in selecting the resolution), it doesn't really make sense to parse the configuration file of `youtube-dl`.

But I will try to fix the code to select the nearest available resolution, when the selected resolution is not available.
