### ISSUE TITLE
Duplication of history-entries

### ISSUE THREAD

**Issue by zensubz** [trizen/youtube-viewer#362]
Would it be possible to ignore an already-existing entry in the *-history.txt files? The same (search) word gets re-added everytime I search using that keyword (or reload that word from the history menu in gtk-ui). Thanks.

**Comment by trizen** [comment]
This is intentional, because the history menu includes the most recent N searches (deduplication is done internally when loading the history file, keeping only the most recent searches). By not storing a keyword if it already exists, it breaks the purpose of this feature.

For example, you searched for "x" last year. Then today you search for "x" again. It's more helpful to have "x" in the most recent searches, than to not include it again in the history file.

Also, appending a line into a file is cheaper than rewriting the file entirely.

**Comment by zensubz** [comment]
I agree, deduplication is done when the history file is loaded and I don't see multiple entries of the same keyword/search-entry (via gtk-ui history menu). In my humble opinion, if a particular keyword already exists in the history.txt file then it could be shifted accordingly so that it gets into most-recent searches. Just a suggestion.
