### ISSUE TITLE
Upgrading YTV

### ISSUE THREAD

**Issue by SlidingHorn** [trizen/youtube-viewer#377]
I know this is basic stuff, but I have a case of The Stupid today:

I originally installed `youtube-viewer` 3.7.8 a while back, and have been unable to use my desktop for a while. I now have it back, and I'd like to upgrade to the new version (3.9.2), but I'm unsure exactly how that process works....

- If I just go into the source directory and build it, will it find/remove the old version before installing?
- Will I keep my subscriptions, etc.?

**Comment by trizen** [comment]
When installing a new version of `youtube-viewer`, the old source-code files will be replaced with the new ones.

But, the config-files (in `~/.config/youtube-viewer`) will not be replaced (only updated, if necessary). Therefore, no user-settings should be lost.

However, if possible, it's preferable to install `youtube-viewer` with your package manager, rather than installing it directly. In this way, you will be able to easily remove it at a later time. Otherwise, you will have to remove it manually (i.e.: by locating and removing the source-code files from your system).

See also: https://github.com/trizen/youtube-viewer#availability

**Comment by SlidingHorn** [comment]
The last version shown on the ppa listed for me (ubuntu) is even older than the one I have installed, so building seems to be the way to go.

The removing source code files won't be an issue, as I keep any source directories  separate (i.e. I still have the 3.7.8 source files in a specific directory)

So basically, I just delete the old source directory, enter the new one, run the commands to build, and I'm all set?

Thanks for your time and he response(s)

**Comment by trizen** [comment]
It's also possible to use `youtube-viewer` without having to install it, by executing the following commands:

```console
    cd /tmp
    wget https://github.com/trizen/youtube-viewer/archive/master.zip -O youtube-viewer-master.zip
    unzip -n youtube-viewer-master.zip
    cd youtube-viewer-master/bin
    ./youtube-viewer
```
