### ISSUE TITLE
Lag/Out of Sync when Rewinding

### ISSUE THREAD

**Issue by harris221212** [trizen/youtube-viewer#424]
If you open a video with youtube-viewer, it will play fine, but if you try to skip back 5 seconds using the left arrow key, then it glitches. The video will play, then the video will stop and the audio will play, then the video speeds up until it catches back up to where you were. 

Running youtube-viewer and also gtk version, happens in both, on Ubuntu 22.04.1 LTS.

**Comment by trizen** [comment]
This is an `mpv` issue...

**Comment by harris221212** [comment]
> This is an `mpv`/`ffmpeg`/`youtube` issue...

Previously I was on Ubuntu 22.04, and it was happening with both youtube-viewer, and with just giving mpv the url directly. However I moved to arch and it only seems to be happening with youtube-viewer. Just passing the link to mpv directly and the skipping is seamless. Is youtube-viewer using an older version of mpv?

**Comment by trizen** [comment]
There are some differences on how `mpv`/`yt-dlp` extracts the YouTube streaming URLs, compared to `youtube-viewer`.

Some workarounds for this issue, would be:

* Disabling `dash_support` in the configuration file. (`dash_support => 0,`)

Or passing the YouTube URLs directly to `mpv`, by making the following change in the configuration-file:

```perl
mpv => {
        arg => "--really-quiet --force-media-title=*TITLE* *URL*",
        cmd => "mpv",
        fs => "--fullscreen",
        novideo => "--no-video",
        srt => "--sub-file=*SUB*",
      },
```

**Comment by harris221212** [comment]
> 

Disabling Dash supported worked, but the resolution is then only 640p. 

Passing the URL directly didn't affect the resolution, however the issue still happens.

**Comment by trizen** [comment]
> Passing the URL directly didn't affect the resolution, however the issue still happens.

That's weird. Because it should be equivalent with executing `mpv YOUTUBE-URL`.

Another possible workaround would be setting `force_fallback => 1,` in the configuration file, which will make `youtube-viewer` to always use `yt-dlp` (or the invidious instances) for extracting the YouTube URLs.

Although, it may not work, because I suspect it's an `mpv`/`ffmpeg` issue, having issues with syncing the audio file and the video file at the same time when navigating backwards and forwards.

**Comment by randomcoder67** [comment]
(Commenting from different account). I came back to this issue recently when trying to get around YouTube's annoying adblock-blocking stuff. 

You're right about it being to do with having a separate audio and video file, as if you use the `22` format (the 720p one you get if you use `mpv --ytdl-format=best`), then the issue doesn't occur. It still occurs in when setting the resolution to 720p in `gtk-youtube-viewer`, as it's using separate audio streams (I assume, as the audio is opus but the `22` format uses `aac`, the one `youtube-viewer` is using looks much better visually.

Adding `hr-seek=yes` to mpv.conf fixes the issue, not sure if it has an other drawbacks though, I don't fully understand what it does.

**Comment by pitsi** [comment]
Sorry for bringing this to the surface, but I am having the same issue.

First and foremost, since I use mpv many times in a day and outside youtube-viewer, how viable is `hr-seek=yes` for everyday use?

Second, the only thing that is dash related in youtube-viewer.conf now is `dash_segmented => 1,`. Is that the same as `dash_support => 0,` mentioned above.

Debian testing/unstable x64, mpv 0.39, ffmpeg 7.1, perl 5.40, yt-dlp 2024.12.23 and youtube-viewer 3.11.3.

**Comment by pitsi** [comment]
I found a workaround, thanks to mpv's `profile-cond` parameter! 
Adding this to mpv.conf makes the videos play at format 18
```
[youtube-viewer]
profile-cond=path:match(youtubei.googleapis.com)
ytdl-format=18
```
Format 18 is 360p video and audio in one mp4 file. Yes, it is only 360p because google removed format 22 (720p video and audio in one mp4 file) months ago, but it is way better than the dash throttling garbage which google forces on us, has a buffer of like 5 sec max and the forementioned seeking issue. If I find a way to use hls stream and if they do not have the same throttling and seeking issues like the dash ones, i will repost for any needed changes.

Of course, you can name the profile anything you like, not just `youtube-viewer`.
