### ISSUE TITLE
How do I change the default resolution?

### ISSUE THREAD

**Issue by Hund** [trizen/youtube-viewer#59]
This is probably not the right place, but I couldn't find any other place to put my question.

I'm using youtube-viewer with the GUI and I cant seem to change the default resolution. It seems to be using 420p instead of the original resolution. How do I change that?

**Comment by trizen** [comment]
Most videos with a higher resolution than 720p doesn't have an audio portion, so youtube-viewer will skip those resolutions to fallback to the highest resolution available which actually works.

For example, [this video](https://www.youtube.com/watch?v=Qrl__J4vYok) has an 1080p resolution on YouTube, but can only be played at 720p by youtube-viewer, because the 1080p resolution has the sound portion in a separate file.

**Comment by Hund** [comment]
720p should be enough. Im often just viewing the video on half of my screen. But even then the quality is crap. :(

**Comment by trizen** [comment]
What is your version of youtube-viewer? (`youtube-viewer --version`)

**Comment by Hund** [comment]
Version 3.1.1.

**Comment by Hund** [comment]
Im using the package gtk-youtube-viewer from AUR.

**Comment by trizen** [comment]
1080p is back!!! (https://github.com/trizen/youtube-viewer/commit/1ed3e95af930c1e4c2f338daf432df7509287ecc)

**Comment by Hund** [comment]
Sweet! :) Your welcome! I really like youtube-viewer.
