### ISSUE TITLE
include mpg123 player

### ISSUE THREAD

**Issue by pekman1** [trizen/youtube-viewer#66]
Hello, I really really like this program, use it every day. A great work you do actually. Sorry offtopic, but had to thank for the great work.

Well, I'm trying to run mpg123 on youtube viewer, however I am not succeeding

Added the following session player:

mpg123 => {
                                 arg => "--stereo --float  --control --title",
                                 cmd => "wget -q -O - `youtube-dl -g $url`| ffmpeg -i - -f mp3 -vn -acodec libmp3lame -| mpg123",
                                 fs => "--fullscreen",
                                 novideo => "--no-video",
                                 srt => "--sub '%s'",
                                },

from what I could see, I am not able to capture the url command sent by youtube-viewer.

I appreciate any help

Use the version cli

**Comment by trizen** [comment]
Hello! I'm glad you enjoy youtube-viewer. :)

I just implemented a way for capturing the video URL from youtube-viewer, among some values. For URL, the token is `%URL%`, which will get replaced by the current video URL.

Other tokens are, briefly, described here: https://github.com/trizen/youtube-viewer/commit/bea8b4732e91ebd79a159f57e598cae1f062d8dc

Now, you can edit the mpg123 player to:
```perl
    mpg123 => {
              arg => "",
              cmd => "wget -q -O - %URL% | ffmpeg -i - -f mp3 -vn -acodec libmp3lame - | mpg123 -",
              fs => "",
              novideo => "",
              srt => "",
         },
```

Out of curiosity: why are you using `ffmpeg` + `mpg123`, instead of going with `mpv` with the `--no-video` option?
