### ISSUE TITLE
youtube-viewer -S shows no subscriptions

### ISSUE THREAD

**Issue by cirrusUK** [trizen/youtube-viewer#75]
Recently running above command only shows one generic entry 
1. https://youtube.com/devicesupport (by youtubehelp) (03:56)
i guess you tube have changed something ..again
regards.

**Comment by trizen** [comment]
The version of youtube-viewer which is in the Arch Linux community repository is out-of-date. Use youtube-viewer-git or gtk-youtube-viewer from AUR.

But, unfortunately, the support for subscriptions is not perfect in the latest version of youtube-viewer, due to the lack of support from the YouTube APIv3. See: https://github.com/trizen/youtube-viewer/issues/74

**Comment by cirrusUK** [comment]
thanks
