### ISSUE TITLE
sh: 1: https:// ... : not found

### ISSUE THREAD

**Issue by gainloop** [trizen/youtube-viewer#76]
I'm using the current version from the master on a Debian wheezy install. Searching for videos works fine, but once a video is selected I get an error message of the following kind: 

use of unitialized value in join or string at /usr/local/bin/youtube-viewer line 3340
sh: 1: https://r4---sn-uxaxovg-5goe.googlevideo.com/videoplayback?pl=20&mv=m&mt=1431033040&ms=au&id=o-APlblCQ0kg1GskbQ0co1GNzAWKssN764xEu72AM84Jcp&keepalive=yes&expire=1431054738&gir=yes&ip=666.666.666.666&mm=31&source=youtube&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&lmt=1397397499552715&requiressl=yes&clen=57304451&initcwndbps=2750000&key=yt5&fexp=907263%2C908415%2C934954%2C938028%2C9405194%2C9405702%2C9408142%2C9408597%2C9408708%2C9408787%2C9408915%2C9409252%2C9412524%2C9412774%2C9413209%2C948124%2C948913%2C952612%2C952637%2C952642%2C963203&signature=09349D80428144FB01DCF2344D8CE6BADC5E605D.6A8C4608C480C38E9367CC9F8FFBB28614EC6A66&sver=3&ipbits=0&upn=Lr94fc1bbsg&itag=248&mime=video%2Fwebm&pcm2cms=yes&dur=249.560: not found

---
perl--version: 
This is perl 5, version 20, subversion 2 (v5.20.2) built for i586-linux-gnu-thread-multi-64int
(with 51 registered patches, see perl -V for more detail)
 
GL

**Comment by trizen** [comment]
This is because no supported video player has been found on your system.

To solve this issue, open the configuration file (`.config/youtube-viewer/youtube-viewer.conf`) and change the value of `video_player_selected` to a value that exists inside the `video_players` structure.

See: https://github.com/trizen/config-files/blob/master/.config/youtube-viewer/youtube-viewer.conf#L51
