### ISSUE TITLE
mkdir /.cache: Permission denied at /usr/bin/youtube-viewer line 499

### ISSUE THREAD

**Issue by Hund** [trizen/youtube-viewer#82]
This is what happens when I try to start the application:

>$ youtube-viewer 
>mkdir /.cache: Permission denied at /usr/bin/youtube-viewer line 499.

Is is trying to find the cache-folder in the root-folder instead of the home-folder?

**Comment by trizen** [comment]
As suggested by https://github.com/trizen/youtube-viewer/issues/73, it first tries the `$XDG_CACHE_HOME`; when defined, this directory will be used, otherwise it defaults to `~/.cache/`.

The problem appears when `$XDG_CACHE_HOME` is not defined and the application is first executed as root, because the `cache_dir` is defined only once.

To solve this issue, change the value of `cache_dir` inside the configuration file.

**Comment by Hund** [comment]
I have never run the application as root. But I did change the path for the cache as it was pointing to "/.cache" for some reason. :) And it works just fine now. Thank you!

**Comment by trizen** [comment]
It's good that it works now. I've added an extra check just to be sure that `$XDG_CACHE_HOME` is writable, which should fix this issue. Thanks for reporting this.
